### ISSUE TITLE
ER図作成

### ISSUE THREAD

**Issue by miura-taiga** [miura-taiga/dust-hunters#5]
## ブランチ名
※あくまで仮のものなので、必要に応じて変更していただいても構いません。
`feature/add-er-diagram`

## 概要
本アプリのER図を作成して下さい。

## 目的
カラム名,テーブル名,型,テーブル間のつながりを明確しておくことで開発時のイレギュラーを防ぐため

## 確認ポイント

※あくまで仮のものなので、必要に応じて変更していただいても構いません。
修正した際はPRにて変更点を記載してください。

- [ ] **ユーザーテーブルが作成されていること**
- [ ] **クエストテーテーブルが作成されていること**
- [ ] **ユーザーとクエストを紐づける中間テーブルが作成されていること**
- [ ] **モンスターテーブルが作成されていること**
- [ ] **ギルドカードテーブルが作成されていること**
- [ ] **テーブル間のリレーショナルが正しい関係になっていること**
  - [ ] Users → UserQuests（1対多）
  - [ ] Quests → UserQuests（1対多）
  - [ ] Quests → Monsters（1対1）
  - [ ] GuildCards → Users（1対多）
  - [ ] GuildCards → Quests（1対多）
  - [ ] GuildCards → Monsters（多対1）

## 補足
その他、必要事項がありましたらプルリクエスト時に記載してください。

**Comment by shota-hope** [comment]
提出ありがとうございます。

- usernameとmonsternameカラムについて、それぞれ単純にnameで良いかなと思うのですがいかがでしょうか。
ご確認よろしくお願いします。

**Comment by miura-taiga** [comment]
レビューいただきありがとうございます。
`username`や`monstername`という表記にした理由としましては今後〇〇nameというカラムが追加された時に何のnameかわかるようにこのような表記にしました。ですが、今後追加予定がありそうなカラムのケースを考えてみましたが、見つからなかったためそれぞれ`name`としました。
ご確認のほどよろしくお願いいたします。

## 変更内容

- `username`→`name`, `monstername`→`name`
- Questsテーブルの不要なコメントアウトを削除

## 変更後

[![Image from Gyazo](https://i.gyazo.com/be7903363c0b59d9feddf1c398172ba6.png)](https://gyazo.com/be7903363c0b59d9feddf1c398172ba6)
