### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by miura-taiga** [miura-taiga/dust-hunters#6]
## 概要
本アプリのissueを作成してください。

## 内容

下記フォーマットに沿う形で提出してください。

## ■Webアプリの概要

このWebアプリ「Dust Hunters（ダストハンター）」は、日常の掃除をゲーム感覚で楽しく続けることを目的としたアプリです。ユーザーは掃除クエストに挑戦し、タイマーが終了するとモンスターを討伐し、図鑑に登録することができます。モンスターを倒すことで日々の掃除のモチベーションを高め、習慣化を促進します。掃除が習慣化できない人や、ゲーム性のあるレベル上げが好きな人、モンスターハンターが好きな人にとって、日々の掃除をより楽しくするためのアプリです。

## ■ProjectsのURL

https://github.com/users/miura-taiga/projects/4

## ■MVPリリースまで
- [ ] Rails x Next.jsの環境構築(済)
- [ ] RailsをRender.com,Next.jsをVercelへデプロイ(済)
- [ ]  トップページ
- [ ] Google認証
- [ ] クエスト一覧機能
- [ ] モンスター討伐機能
- [ ] 図鑑機能
- [ ] X 共有機能

## ■MVP後
- [ ] 管理画面(クエスト追加)
- [ ] HR機能
- [ ] アバター機能
- [ ] 掃除箇所のグラフ化機能
- [ ] 日々の継続を記録化機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] 独自ドメイン
- [ ] Rspec

## ■MVPレビュー依頼予定日
予定日：2024年 9月 29日

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by miura-taiga** [comment]
レビューいただきありがとうございます。
修正いたしました。ご確認よろしくお願いいたします。

***

## 変更内容

- Google認証のストリートポイントの見直し(5 → 3)

issue作成期間から現在までに、技術検証を重ね実装内容の把握ができたため、見積もりを変更しました。

**対象issue** : [#1](https://github.com/users/miura-taiga/projects/4/views/1?pane=issue&itemId=76108559),[#5](https://github.com/users/miura-taiga/projects/4/views/1?pane=issue&itemId=78237495)


- X 認証のストリートポイントの見直しおよび削除(5 → 3, Rails側を削除)

issue作成期間から現在までに、技術検証を重ね実装内容の把握ができたため、見積もりを変更しました。
実装にRailsの実装が不要のため削除しました。

**対象issue** : [#16](https://github.com/users/miura-taiga/projects/4/views/1?pane=issue&itemId=78277491)

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- X 共有機能
- 図鑑機能
